name: hidrotec
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scipy
  - pandas
  - requests
  - h5py
  - netCDF4
  - xarray
  - dask
  - bottleneck
  - pygrib
  - pip:
    - paramiko
    - copernicusmarine
    